version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    # image: apache/airflow:3.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.default
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__WEBSERVER__AUTHENTICATE: 'false'
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      # AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
      # AIRFLOW__AUTH__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8090:8080"
    command: >
      bash -c "
      echo 'Waiting for PostgreSQL...';
      while ! pg_isready -h postgres -p 5432 -U airflow -d airflow_db; do
        sleep 2;
      done;

      echo 'Migrating DB...';
      airflow db migrate;

      echo 'Starting Airflow...';
      airflow dag-processor &
      airflow scheduler &
      exec airflow api-server
      "



  # airflow-scheduler:
  #   image: apache/airflow:3.1.0
  #   container_name: airflow_scheduler
  #   healthcheck:
  #     test: ["CMD-SHELL", "airflow db check || exit 1"]
  #     interval: 5s
  #     retries: 10
  #   depends_on:
  #     - postgres
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
  #     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  #     AIRFLOW__CORE__FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
  #     AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
  #     AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
  #     # AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
  #     AIRFLOW__LOGGING__LOG_SERVER_PORT: 8793
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins
  #   command: >
  #     bash -c "
  #     echo 'Waiting for PostgreSQL...';
  #     while ! pg_isready -h postgres -p 5432 -U airflow -d airflow_db; do sleep 2; done;
  #     echo 'Upgrading DB...';
  #     airflow db upgrade;
  #     echo 'Starting scheduler...';
  #     exec airflow scheduler
  #     "

  # airflow-api:
  #   image: apache/airflow:3.1.0
  #   container_name: airflow_api
  #   depends_on:
  #     airflow-scheduler:
  #       condition: service_healthy
  #   environment:
  #     AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.default
  #     AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs1
  #     # AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins
  #   ports:
  #     - "8090:8080"
  #   command: >
  #     bash -c "
  #     echo 'Waiting for PostgreSQL...';
  #     while ! pg_isready -h postgres -p 5432 -U airflow -d airflow_db; do sleep 2; done;
  #     echo 'Starting API server...';
  #     exec airflow api-server
  #     "





volumes:
  postgres_data: